[project]
name = "finance-news-etl"
version = "0.1.0"
description = "Mini ETL: financial news -> sentiment -> Postgres"
requires-python = ">=3.11"
dependencies = []

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
